### ISSUE TITLE
Servers are down

### ISSUE THREAD

**Issue by TubeGame** [idkajsjsjehdus/TubeLuncher#1]
PLEASE FIX THE SERVER

**Comment by idkajsjsjehdus** [comment]
Servers are down due to crash bug. They will be back up very soon!

**Comment by TubeGame** [comment]
How long

**Comment by idkajsjsjehdus** [comment]
Maybe like an hour or so.

**Comment by TubeGame** [comment]
BRO THATS SO LONG

**Comment by idkajsjsjehdus** [comment]
Well I'm sorry but I cant do anything about it right now.

**Comment by TubeGame** [comment]
OMG BRO FUCK DAWG

**Comment by idkajsjsjehdus** [comment]
I'm going to close this comment now. And I told you one hour before its back up stop crying like a bitch.

**Comment by idkajsjsjehdus** [comment]
Please chill out.
